# Copyright (c) 2019 Status Research & Development GmbH
# Licensed under either of
#  * Apache License, version 2.0, ([LICENSE-APACHE](LICENSE-APACHE))
#  * MIT license ([LICENSE-MIT](LICENSE-MIT))
# at your option.
# This file may not be copied, modified, or distributed except according to
# those terms.

# In theory, this simple file could be generated by c2nim. In practice, c2nim
# can't handle "__attribute__((...))".

proc get_backtrace_c*(): cstring {.importc: "get_backtrace_c",
                              header: "libbacktrace_wrapper.h".}

