name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      test-command: |
        env NIMLANG=c nimble test_asan
        env NIMLANG=cpp nimble test_asan
        env NIMLANG=c nimble test
        env NIMLANG=cpp nimble test

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2  # In PR, has extra merge commit: ^1 = PR, ^2 = base

      - name: Check NPH formatting
        uses: arnetheduck/nph-action@v1
        with:
          version: 0.7.0
          options: "./. *.nim*"
          fail: true
          suggest: true
